version: '3'
services:
  frontend:
    image: erickmayorgar/so1-p1-frontend:1.0.0
    build:
      context:  ./frontend # Carpeta donde se encuentra tu código frontend (React)
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Puedes cambiar el puerto si es necesario
    environment:
      - REACT_APP_API_URL=http://backend:5000  # URL de la API backend
    networks:
      - app-network

  backend:
    image: erickmayorgar/so1-p1-backend:1.0.0
    build:
      context: ./backend  
    ports:
      - "5000:5000"  
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SO1Proyecto1
    ports:
      - "3306:3306"  # Puedes cambiar el puerto si es necesario
    volumes:
      - ./database:/app/database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
